# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: sabore_development

  cable:
    <<: *default
    database: sabore_development

  queue:
    <<: *default
    database: sabore_development

test:
  primary:
    <<: *default
    database: sabore_test

  cable:
    <<: *default
    database: sabore_test

  queue:
    <<: *default
    database: sabore_test

production:
  primary:
    <<: *default
    database: sabore_production

  cable:
    <<: *default
    database: sabore_production

  queue:
    <<: *default
    database: sabore_production
